### ISSUE TITLE
Legends overlapping layer selection

### ISSUE THREAD

**Issue by barrychocolate** [eightsixtwo/flexdashboards#2]
When multiple layers are selected the legends stack up.  If too many layers are selected the legends can overlap the layer selection box .  

To replicate add the Local Population, Costs and overheads layers.

**Comment by barrychocolate** [comment]
![image](https://user-images.githubusercontent.com/23360661/72681373-bef0c680-3aba-11ea-8764-0965e71a77c9.png)

**Comment by eightsixtwo** [comment]
Good spot.  This is simply fixed by changing the legend position - 'position = "bottomleft"'
